### ISSUE TITLE
gitlab CI

### ISSUE THREAD

**Issue by sephiroth6** [MCUdude/MCUdude_corefiles#12]
Hello @MCUdude and @per1234,
I would like to use arduino-ci-script with gitlab-ci, is it possible? How can I do?
Thank for reply

**Comment by per1234** [comment]
I haven't done any testing of arduino-ci-script with GitLab CI, though making it less Travis CI-specific and testing on the most popular CI services is definitely on my "to-do" list.

Certain functions of arduino-ci-script do currently use Travis CI-specific environment variables, as I have listed here: https://github.com/per1234/arduino-ci-script/issues/20. I believe those are going to be the report functions, which are not really part of the core functionality of arduino-ci-script.

So I'd think you could use arduino-ci-script as-is with GitLab CI as long as you don't use the report functions but that's only a guess.

Anyways, this is not an appropriate place to discuss arduino-ci-script since it's not really related to this repository. I'm happy to help you out over on the [Arduino Forum](http://forum.arduino.cc/). If you find specific problems with arduino-ci-script preventing it from working with GitLab CI you're welcome to open a pull request or issue report at https://github.com/per1234/arduino-ci-script but please don't open issues there only asking for support as I prefer to keep that sort of discussion on the Arduino Forum.

**Comment by sephiroth6** [comment]
Thanks for exhaustive and fast reply.
I understand your purpose and I will do the next on Arduino Forum, at this time I didn't know where ask for this specific repo. Actually I'm using https://github.com/Actinius/docker-arduino-ci on gitlab, but I would change, so I will try your as-is.
Regards
